@startuml 05_sync_achievements
title Синхронизация достижений пользователя

start

:Вызвать syncUserAchievements(userId);

:Инициализировать счётчик итераций = 0;

repeat

  partition "Сбор контекста пользователя" {
    fork
      :XP пользователя;
    fork again
      :Кол-во интервью (всего);
    fork again
      :Кол-во завершённых\nинтервью;
    fork again
      :Кол-во отменённых\nинтервью;
    fork again
      :Средний / лучший /\nпоследний балл;
    fork again
      :Текущий стрик (дней);
    fork again
      :Дней с последнего\nинтервью;
    fork again
      :Кол-во уже выданных\nдостижений;
    fork again
      :Статистика за сегодня;
    end fork
    :Сформировать контекст;
  }

  :Загрузить все доступные\nдостижения (отсортированные\nпо createdAt);

  :Инициализировать список\nновых наград = [];

  repeat
    :Взять следующее достижение;

    if (Достижение уже выдано\nпользователю?) then (да)
      :Пропустить;
    else (нет)
      :Вычислить формулу\nдостижения с контекстом;

      if (Формула = true?) then (да)
        :Добавить в список\nновых наград;
      endif
    endif

  repeat while (Ещё достижения?) is (да)
  ->нет;

  if (Список новых наград пуст?) then (да)
    :Прервать цикл;
  else (нет)
    :INSERT всех новых наград\nв БД;
    :Увеличить счётчик итераций;
  endif

repeat while (Новые награды были выданы?) is (да)
->нет;

:Вернуть общее количество\nвыданных достижений;

stop
@enduml
