@startuml 07_file_upload
title Загрузка файла (аватар / изображение скрипта)
skinparam ActivityBackgroundColor White

|Клиент|
start

:Пользователь выбирает файл;

|Сервер|

:Сгенерировать S3-ключ\nи подписанный PUT URL;

:Вернуть {url, key};

|Клиент|

:Загрузить файл напрямую в S3\n(HTTP PUT на подписанный URL);

if (Загрузка успешна?) then (да)
  :Сохранить key в форме;
else (нет)
  :Показать ошибку;
  stop
endif

:Передать key при сохранении формы;

|Сервер|

:Сохранить key в запись\nскрипта / пользователя в БД;

stop
@enduml
