@startuml Conceptual DB Diagram

skinparam linetype ortho
skinparam EntityBorderColor #555
skinparam EntityFontSize 12

entity "Пользователь" #White {
  имя
  email
  роль
  XP
}

entity "Категория" #White {
  название
}

entity "Сценарий" #White {
  название
  описание
  контекст
}

entity "Вопрос" #White {
  текст
}

entity "Критерий сценария" #White {
  содержание
  тип
}

entity "Критерий вопроса" #White {
  содержание
}

entity "Сессия интервью" #White

entity "Сообщение" #White {
  текст
}

entity "Достижение" #White {
  название
  описание
}

entity "Жалоба" #White {
  причина
}

' Relations
"Пользователь" ||--o{ "Сценарий" : "создаёт (как эксперт)"
"Пользователь" ||--o{ "Сессия интервью" : "проходит"
"Пользователь" }o--o{ "Достижение" : "получает"
"Пользователь" ||--o{ "Жалоба" : "подаёт"

"Категория" ||--o{ "Сценарий" : "классифицирует"

"Сценарий" ||--o{ "Вопрос" : "содержит"
"Сценарий" ||--o{ "Критерий сценария" : "имеет"
"Сценарий" ||--o{ "Сессия интервью" : "используется в"
"Сценарий" ||--o{ "Жалоба" : "является предметом"

"Вопрос" ||--o{ "Критерий вопроса" : "имеет"

"Сессия интервью" ||--o{ "Сообщение" : "содержит"

@enduml
